### ISSUE TITLE
每日提醒的动漫模块，用的仍然是NewsGroupWhiteList

### ISSUE THREAD

**Issue by Robinyer** [LinHeLurking/mirai-news-reporter#10]
![image](https://user-images.githubusercontent.com/34450363/140442163-82a43adf-a72e-49d2-9597-ca8d52703257.png)
App.kt 60行

**Comment by LinHeLurking** [comment]
谢谢提醒, 我会去再检查一下的.

**Comment by LinHeLurking** [comment]
已于 1.3.1 修复

**Comment by LinHeLurking** [comment]
之前的 CI 有问题，直接下载最新版的吧：
https://github.com/LinHeLurking/mirai-news-reporter/releases/tag/latest
