### ISSUE TITLE
NoAnimeException: Not found info for date: 5-16

### ISSUE THREAD

**Issue by gimfia** [LinHeLurking/mirai-news-reporter#16]
![image](https://user-images.githubusercontent.com/54408388/168503051-528f451c-f708-4060-b95e-80e5a321553b.png)
报错了

**Comment by qyh214** [comment]
是不是更新到最新了，我也遇到了，到了第二天就会报错

**Comment by LinHeLurking** [comment]
谢谢反馈，我检查一下

**Comment by LinHeLurking** [comment]
没能复现这个问题呀。
这个输出说明当天没有番剧。不过我查了 B 站的目录，5-16 是有一部番剧的，而且只有一部。我刚才试着重新抓了一下 5-16 的数据，能正常输出结果的。是不是有可能当时 B 站的数据没更新，那天就没有数据呢？如果某天的番剧列表真的是空的话，插件确实会是这个反应：会提示 NoAnime。

**Comment by gimfia** [comment]
> 没能复现这个问题呀。 这个输出说明当天没有番剧。不过我查了 B 站的目录，5-16 是有一部番剧的，而且只有一部。我刚才试着重新抓了一下 5-16 的数据，能正常输出结果的。是不是有可能当时 B 站的数据没更新，那天就没有数据呢？如果某天的番剧列表真的是空的话，插件确实会是这个反应：会提示 NoAnime。

如果是没番剧的话，感觉提示语句换成“今日无番剧更新”之类的更好，因为发送的语句还是“这是今天的番剧”，但是没发图片

**Comment by LinHeLurking** [comment]
> 

是个好的建议，我之后修改一下

**Comment by LinHeLurking** [comment]
最新版本已经修复这个问题并且优化了提示，欢迎继续反馈
