### ISSUE TITLE
能否添加通过修改配置文件的方式修改回复语句和触发词

### ISSUE THREAD

**Issue by yakumocheeeeeen** [LinHeLurking/mirai-news-reporter#19]
目前时只能通过重新打包源码啥的来实现

**Comment by LinHeLurking** [comment]
很好的建议，实际上最开始我就想那么做的，只不过后来太懒了没改 /w\
等我这两天摸一个出来。

**Comment by LinHeLurking** [comment]
https://github.com/LinHeLurking/mirai-news-reporter/releases/tag/v1.4.0-rc

已添加该功能。

**Comment by LinHeLurking** [comment]
新命令的说明更新在 README 中。

https://github.com/LinHeLurking/mirai-news-reporter
