### ISSUE TITLE
已经拉入白名单仍然无法今日番剧

### ISSUE THREAD

**Issue by w1945512171** [LinHeLurking/mirai-news-reporter#20]
![QQ图片20220819145828](https://user-images.githubusercontent.com/111542766/185562068-56a59046-fd4a-437f-bbe7-081751126a05.jpg)
![QQ图片20220819145834](https://user-images.githubusercontent.com/111542766/185562073-f39620a6-3677-432e-9196-1334ecc72f28.jpg)
![QQ图片20220819145846](https://user-images.githubusercontent.com/111542766/185562081-5a8453a5-6721-4228-a3da-ece541255f5d.jpg)

**Comment by LinHeLurking** [comment]
感谢反馈，晚上看看

**Comment by w1945512171** [comment]
okok

**Comment by w1945512171** [comment]
谢谢了

**Comment by LinHeLurking** [comment]
仔细检查了一下，没有复现这个问题。会不会是因为新闻的白名单和番剧白名单是分开的，只加了一边的话，另一边还是没加的。

**Comment by w1945512171** [comment]
是的是的，是我没看到还有一个番剧的白名单谢谢哈

**Comment by w1945512171** [comment]
是的是的，是我没看到还有一个番剧的白名单谢谢哈

**Comment by LinHeLurking** [comment]
> 是的是的，是我没看到还有一个番剧的白名单谢谢哈

其实这里是我弄的有点不直观了。我等会发一个新版本，可以用一个命令操作两个白名单。

**Comment by w1945512171** [comment]
wow，期待期待，一会儿就去更新体验下
