### ISSUE TITLE
【BUG】本周停更的番剧会留下空白

### ISSUE THREAD

**Issue by KaRuichin** [LinHeLurking/mirai-news-reporter#26]
![image](https://user-images.githubusercontent.com/69111766/210118132-7123191a-bba0-40df-aeaf-715725ed4b62.png)
![S63J~0$H6J)O9)1}~4U88QS](https://user-images.githubusercontent.com/69111766/210118143-33638c14-33c4-49ac-9982-52fe910f5c11.png)
如图所示

**Comment by LinHeLurking** [comment]
谢谢反馈，1.4.5 版本已修复
