### ISSUE TITLE
每日新闻知乎停更

### ISSUE THREAD

**Issue by MskTmi** [LinHeLurking/mirai-news-reporter#30]
[每天60秒读懂世界](https://zhuanlan.zhihu.com/p/665616411) 停更
![image](https://github.com/LinHeLurking/mirai-news-reporter/assets/87525977/f5045359-d9ad-4db1-83dc-1f3e8853792f)

每天早上会获取作者最新点赞的帖子

**Comment by LinHeLurking** [comment]
查了一下，公众号上好像是仍然在更新的。不过爬取微信数据可能太难了。我找找看有没有别的替代方案。

**Comment by qyh214** [comment]
期待更新~话说摸鱼人日历那个是不是因为有图片爬，微信公众号的爬目前没找到比较好的办法，哦，找到一个，不知道能不能帮到大佬，也可以选择让大家自己去搞api key，你只做接入，https://www.tianapi.com/apiview/117

**Comment by LinHeLurking** [comment]
最新的 1.6.0 版本使用了网友提供的 API，已经修复了每日新闻的问题，可以正常使用。

**Comment by MskTmi** [comment]
终于又有新闻看了，感谢维护
