### ISSUE TITLE
删除新闻列表后重启mirai,会自动把新闻加上

### ISSUE THREAD

**Issue by MR-MonkeyRay** [LinHeLurking/mirai-news-reporter#31]
### 版本信息: 

- mirai: 2.16.0
- news-reporter: 1.5.0

### 复现:

1. 给群添加anime和moyu

![add](https://github.com/LinHeLurking/mirai-news-reporter/assets/19302557/e2ff6201-d6c3-483b-a761-5c63278f98a3)

2. 重启mirai再看列表

![add-2](https://github.com/LinHeLurking/mirai-news-reporter/assets/19302557/20f30466-6a77-426e-a2f4-79915e4c8f1e)

3. 手动把news删掉

![remove](https://github.com/LinHeLurking/mirai-news-reporter/assets/19302557/6e9ab4dd-d828-4d66-93c3-898605e1e264)

4. 再重启mirai看列表

![remove-2](https://github.com/LinHeLurking/mirai-news-reporter/assets/19302557/b007ae76-d5fd-49a8-9de3-2438806d1967)

**Comment by LinHeLurking** [comment]
不太确定产生原因，可能是命令匹配的问题，也可能是配置存储的问题。我再排查排查。

**Comment by LinHeLurking** [comment]
我的机器人在 console 里登不上了。。。这下束手无策了。。。

**Comment by MR-MonkeyRay** [comment]
> 我的机器人在 console 里登不上了。。。这下束手无策了。。。

用这个版本的txlib试试看?
https://github.com/MrXiaoM/qsign/tree/mirai/txlib/8.9.85

**Comment by LinHeLurking** [comment]
定位到问题了，之前给我 PR 摸鱼功能的老哥把存储 ID 抄下来了，导致摸鱼和新闻白名单冲突了。等会马上发个新版本修复。

**Comment by LinHeLurking** [comment]
已修复，在 release 页面可以看到。
