### ISSUE TITLE
程序无法启动

### ISSUE THREAD

**Issue by kokorousaki** [LinHeLurking/mirai-news-reporter#4]
![image](https://user-images.githubusercontent.com/87707351/132812154-225ea5fd-23cc-4ba3-a8f4-894bd592687e.png)
加了这个new的插件后就无法启动mirai，去掉插件又可以了

**Comment by LinHeLurking** [comment]
谢谢你的反馈，我抽空看一下是为什么。请问这是什么平台，什么版本呢？
