### ISSUE TITLE
只能收到文字看不到图片，后台显示有图片发送可聊天里收不到图片

### ISSUE THREAD

**Issue by Ta-Gii** [LinHeLurking/mirai-news-reporter#5]
唔，我发现插件使用时只能回复“这是今日速报”却收不到图片的问题，我还特地手机电脑登录bot账号，之后再次使用插件也还是同样的问题，请问作者有什么办法嘛？

**Comment by LinHeLurking** [comment]
无法发送图片应该是 mirai 的问题，我看到 mirai 的论坛上有很多人说了这个事情。
